# Generated by Django 5.2.12 on 2026-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncState',
            fields=[
                ('sku', models.CharField(help_text='Stock Keeping Unit from ERP', max_length=255, primary_key=True, serialize=False)),
                ('data_hash', models.CharField(help_text='SHA-256 hash of the transformed product data', max_length=64)),
                ('last_sync_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last successful sync check')),
            ],
        ),
    ]
